[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"
    X-Content-Type-Options = "nosniff"
